server {
    listen 8080;
    server_name _;

    location / {
        root /var/www/hls;

        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
        }

        add_header Cache-Control "no-cache, no-store";
        add_header Access-Control-Allow-Origin *;
    }
}
